modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/UnlikePaladin/ored-cakes/issues"
license = "lgpl-3.0-only"

[[mods]]
modId = "oredcakes"
version = "${version}"
displayName = "Ored Cakes Mod"
authors = "UnlikePaladin"
description = '''
    Makes Ore Cakes a reality
'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/ored-cakes"
logoFile = "ored_cakes.png"

[[dependencies.oredcakes]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oredcakes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.18.2)"
ordering = "NONE"
side = "BOTH"
